### ISSUE TITLE
The extension requires a version of the .NET Framework that is not installed.

### ISSUE THREAD

**Issue by roncli** [ilmax/vs-restart#1]
I am attempting to install this on a fresh Windows 7 Visual Studio 2013 installation, and I am getting the error:

```
The extension could not be installed because the following error occurred:

The extension 'Visual Studio Restart' requires a version of the .NET Framework that is not installed.
```

In addition to not knowing what framework I am missing, I am in an environment where I cannot install any additional .NET frameworks, how can I install this extension?

**Comment by ilmax** [comment]
Hi, the extension have the [.NET Framework 4.5 as a dependency ](https://github.com/ilmax/vs-restart/blob/master/VsRestart/source.extension.vsixmanifest#L16) which should be installed by default when installing VS2013 IIRC.

Since I'm no more using VS2013, you can just send a PR to lower the .NET Framework dependency, or clone and build it yourself.

Update. Looks like the extension manifest is incorrectly too tighten, the correct dependency should be the same as [this one](https://github.com/cyotek/Cyotek.AddProjects/blob/master/src/source.extension.vsixmanifest#L17) to allow .net 4.5 or newer

**Comment by roncli** [comment]
That did the trick, I'll offer a PR.
